apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: public-vps-pool
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: earth
  blocks:
    - cidr: "${public_ip}/32" # Injected from var.PUBLIC_NODE_IP
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: vps-announcement
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: earth
  ipPools:
    - public-vps-pool
  interfaces:
    - ^en.*
    - ^eth.*
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: local-pool
spec:
  nodeSelector:
    matchLabels:
      l2-announce: "true"
  blocks:
    - start: "192.168.2.201"
      stop: "192.168.2.240"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: local-announcement
spec:
  nodeSelector:
    matchLabels:
      l2-announce: "true"
  interfaces:
    - ^en.*
    - ^eth.*
  externalIPs: true
  loadBalancerIPs: true
  serviceSelector:
    matchExpressions:
      - key: io.cilium/lb-ipam-ips-pool
        operator: In
        values:
          - local-pool
