# --- Public IP Pool ---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: public-vps-pool
spec:
  blocks:
    - cidr: "${public_ip}/32" # Injected from var.PUBLIC_NODE_IP
---
# --- L2 Announcement Policy ---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: vps-announcement
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: earth
  interfaces:
    - ^en.*
    - ^eth.*
  externalIPs: true
  loadBalancerIPs: true
