apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: database-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
    argocd.argoproj.io/sync-wave: "1"
spec:
  # MUST use a pgvector / vectorchord enabled image for Immich
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.3.0
  instances: 2

  postgresql:
    shared_preload_libraries:
      - "vchord.so"
      - "pg_stat_statements"

  affinity:
    podAntiAffinityType: required

  storage:
    size: 20Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "cube";

  backup:
    barmanObjectStore:
      destinationPath : "s3://database-backup/immich-db"
      endpointURL: "http://192.168.70.100:9000"
      s3Credentials:
        accessKeyId:
          name: s3-details
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: s3-details
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip