apiVersion: v1
kind: Node
metadata:
  name: talos-worker-01
  labels:
    node-role.kubernetes.io/worker: ""
---
apiVersion: v1
kind: Node
metadata:
  name: talos-worker-02
  labels:
    node-role.kubernetes.io/worker: ""