apiVersion: v1
kind: Namespace
metadata:
  name: coroot-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: coroot.com/v1
kind: Coroot
metadata:
  name: coroot
  namespace: coroot-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  communityEdition: {}

  postgres:
    host: "coroot-db-rw.database-system.svc.cluster.local"
    port: 5432
    database: "coroot"
    user: "coroot"
    passwordSecret:
      name: "coroot-db-app"
      key: "password"
    params:
      sslmode: "disable"

  storeMetricsInClickhouse: true
  nodeAgent: {}
  clusterAgent: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sync-sa
  namespace: coroot-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-sync-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "services"]
    verbs: ["get", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-sync-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-sync-role
subjects:
  - kind: ServiceAccount
    name: secret-sync-sa
    namespace: coroot-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-db-secret
  namespace: coroot-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: secret-sync-sa
      containers:
        - name: sync
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -eo pipefail
              echo "Starting sync..."

              kubectl get secret coroot-db-app -n database-system -o yaml | \
              grep -vE '^  (uid|resourceVersion|creationTimestamp):' | \
              awk '/ownerReferences:/{flag=1;next} /^[^ ]/{flag=0} !flag' | \
              kubectl label --local -f - argocd.argoproj.io/instance- --dry-run=client -o yaml | \
              sed 's/namespace: database-system/namespace: coroot-system/' | \
              kubectl annotate --local -f - argocd.argoproj.io/compare-options=IgnoreExtraneous argocd.argoproj.io/sync-options=Prune=false --dry-run=client -o yaml | \
              kubectl apply -f -

              echo "Sync complete."

              echo "Sync complete."
      restartPolicy: OnFailure
