apiVersion: v1
kind: Namespace
metadata:
  name: authentik-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  namespace: authentik-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-server
  template:
    metadata:
      labels:
        app: authentik-server
    spec:
      containers:
        - name: server
          image: ghcr.io/goauthentik/server:2026.2.1
          args: ["server"]
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                {
                  secretKeyRef:
                    { name: authentik-secrets, key: authentik-secret-key },
                }
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: "authentik-db-rw.database-system.svc.cluster.local"
            - name: AUTHENTIK_POSTGRESQL__USER
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                { secretKeyRef: { name: authentik-db-app, key: password } }
            - name: AUTHENTIK_REDIS__HOST
              value: "authentik-redis-master.authentik-system.svc.cluster.local"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: blueprints-folder
              mountPath: /blueprints/custom # Mounts the whole folder here
      volumes:
        - name: blueprints-folder
          configMap:
            name: authentik-blueprints
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: authentik-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-worker
  template:
    metadata:
      labels:
        app: authentik-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/goauthentik/server:2026.2.1
          args: ["worker"]
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                {
                  secretKeyRef:
                    { name: authentik-secrets, key: authentik-secret-key },
                }
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: "authentik-db-rw.database-system.svc.cluster.local"
            - name: AUTHENTIK_POSTGRESQL__USER
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                { secretKeyRef: { name: authentik-db-app, key: password } }
            - name: AUTHENTIK_REDIS__HOST
              value: "authentik-redis-master.authentik-system.svc.cluster.local"
          volumeMounts:
            - name: blueprints-folder
              mountPath: /blueprints/custom # Mounts the whole folder here
      volumes:
        - name: blueprints-folder
          configMap:
            name: authentik-blueprints
