apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./coroot-deployment/coroot/coroot-db-secret-sync.yaml
  - ./coroot-deployment/coroot/coroot-instance.yaml
  - ./coroot-deployment/coroot-db/coroot-db.yaml
  - ./coroot-operator/application.yaml