apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-pv
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /mnt/latinum/virtualdisks/immich_files
    server: 100.91.97.25
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-pvc
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: immich-nfs-pv
