apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-pvc
  namespace: minecraft-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-mods-pvc
  namespace: minecraft-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi