apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: database-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
    argocd.argoproj.io/sync-wave: "2"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  instances: 2

  affinity:
    podAntiAffinityType: required

  bootstrap:
    recovery:
      source: authentik-db

  storage:
    size: 10Gi
    storageClass: local-path

  backup:
    barmanObjectStore:
      destinationPath: "s3://database-backup/authentik-db"
      endpointURL: "http://192.168.70.100:9000"
      s3Credentials:
        accessKeyId:
          name: s3-details
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: s3-details
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip

  externalClusters:
    - name: authentik-db
      barmanObjectStore:
        destinationPath: "s3://database-backup/authentik-db"
        endpointURL: "http://192.168.70.100:9000"
        s3Credentials:
          accessKeyId:
            name: s3-details
            key: AWS_ACCESS_KEY_ID
          secretAccessKey:
            name: s3-details
            key: AWS_SECRET_ACCESS_KEY