apiVersion: v1
kind: Namespace
metadata:
  name: coroot-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: coroot.com/v1
kind: Coroot
metadata:
  name: coroot
  namespace: coroot-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  communityEdition: {}

  service:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips-pool: "local-pool"
      lbipam.cilium.io/ips: "192.168.2.207"

  postgres:
    host: "coroot-db-rw.database-system.svc.cluster.local"
    port: 5432
    database: "coroot"
    user: "coroot"
    passwordSecret:
      name: "coroot-db-app"
      key: "password"
    params:
      sslmode: "disable"

  storeMetricsInClickhouse: true
  nodeAgent: {}
  clusterAgent: {}
